In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
import matplotlib.pyplot as plt
import nnde

# Element-wise product

How does it work? We need to multiply every row of a matrix (n x m array) by a single value from a vector.

In [2]:
H = np.arange(9).reshape((3,3))
H

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
a = np.array([0.5, 1, 2.75]).reshape((3,1))
a

array([[ 0.5 ],
       [ 1.  ],
       [ 2.75]])

In [4]:
M = H * a
M

array([[  0.  ,   0.5 ,   1.  ],
       [  3.  ,   4.  ,   5.  ],
       [ 16.5 ,  19.25,  22.  ]])

Dit it work as intended? 
Let's compare it by using a naive for loop.

In [5]:
T = np.zeros((3,3))
for i in range(3):
  for j in range(3):
    T[i, j] = M[i,j] - H[i,j] * a[i]
T

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

It requires the vector to be reshaped into (3, 1).
It cannot be a simple (3,) sequence.

In [6]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [7]:
H * b

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

The transpose does not work either as it is a 1d array.

In [8]:
b.T

array([1, 2, 3])

In [9]:
H * b.T

array([[ 0,  2,  6],
       [ 3,  8, 15],
       [ 6, 14, 24]])

It could work as:

In [10]:
(H.T * b).T

array([[ 0,  1,  2],
       [ 6,  8, 10],
       [18, 21, 24]])

But this is more inconvenient than reshaping the vector into 2d (3, 1) array.